import "@/styles/globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

const interSans = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning>
      <body className={`${interSans.className} antialiased`}>{children}</body>
    </html>
  );
}
